[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_ticketing = "EKvx21X9PgjXUFqHwzvZDJGHMJtUkLab3DaL3LZ7nGkW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"
