[toolchain]
anchor_version = "0.30.1"  # `anchor-cli` version to use(requires `avm`)
solana_version = "1.18.22" # Solana version to use(applies to all Solana tools)

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_ticketing = "F4z76S7pDeYY2kGTn4MmzT6sYpAEmkD4WErSQagQ1aQU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"                 # The cluster used for all commands.
wallet = "~/.config/solana/id.json"  # The keypair used for all commands.

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/metaplex_token_metadata_program.so"
