name: Anchor Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.18.22/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version || echo "Solana installation failed"

      - name: Install Anchor
        run: |
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --tag v0.30.1 || echo "Anchor installation failed"
          anchor --version || echo "Anchor not found"

      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Anchor.toml content:"
          cat Anchor.toml || echo "Anchor.toml not found"
          echo "PATH: $PATH"
          echo "Rust version: $(rustc --version)"
          echo "Cargo version: $(cargo --version)"
          echo "Solana version: $(solana --version)"
          echo "Anchor version: $(anchor --version)"

      - name: Build Anchor Program
        run: anchor build
        continue-on-error: true

      - name: Debug Build Failure
        if: failure()
        run: |
          echo "Build failed. Debugging information:"
          echo "Current directory: $(pwd)"
          ls -la
          echo "target directory content:"
          ls -la target || echo "target directory not found"
          echo "programs directory content:"
          ls -la programs || echo "programs directory not found"
          echo "Cargo.toml content:"
          cat Cargo.toml || echo "Cargo.toml not found"

      - name: Run Anchor Tests
        run: anchor test
