name: Anchor Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLANA_VERSION: 1.18.22
  ANCHOR_VERSION: 0.30.1

jobs:
  test:
    name: Run Anchor Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ~/.local/share/solana
            target
          key: ${{ runner.os }}-cargo-solana-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          solana --version

      - name: Install Anchor
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install ${{ env.ANCHOR_VERSION }}
          avm use ${{ env.ANCHOR_VERSION }}
          anchor --version

      - name: Build program
        run: anchor build

      - name: Run tests
        run: |
          solana-test-validator --ledger .anchor/test-ledger --clone-upgradeable-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s --url https://api.mainnet-beta.solana.com &
          sleep 5
          anchor test --skip-local-validator

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: target